### ISSUE TITLE
Error in mailwatch-postfix-relay

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#941] opened 2017-09-01 14:48 UTC
### Issue summary
I get an error when running mailwatch-postfix-relay
### Steps to reproduce
1. run /etc/cron.hourly/mailwatch-postfix-relay

### Expected result
No error should appear, I'm not sure what the actual screen output should be though...

### Actual result
Fatal error: Uncaught exception 'mysqli_sql_exception' with message 'Incorrect time value: '561' for column 'delay' at row 1' in /opt/mailwatch/mailscanner/functions.php:968
Stack trace:
#0 /opt/mailwatch/mailscanner/functions.php(968): mysqli->query('REPLACE INTO mt...')
#1 /opt/mailwatch/mailscanner/mtalogprocessor.inc.php(143): dbquery('REPLACE INTO mt...')
#2 /usr/local/bin/mailwatch_postfix_relay.php(99): MtaLogProcessor->doit('cat /var/log/ma...')
#3 {main}
  thrown in /opt/mailwatch/mailscanner/functions.php on line 968
cat: write error: Broken pipe

### Version and method
- MailWatch Version: [ stable 1.2.5
- Install type: Zip/tarball install
- Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
- Operation System: CentOS 7
- PHP version: 5.4
- Database: MySQL version 5.6.37
- Mail Server: Postfix version 2.10.1
- Used web server: Apache version 2.4.6

### Client configuration 
 - N/A

**Comment by asuweb** [comment] 2017-09-01 15:23
can you post an output from your maillog?  It looks like there is a formatting issue.  Delay should be in the from 00:00:00

**Comment by Skywalker-11** [comment] 2017-09-01 15:24
Probably duplicate of #924

**Comment by quintingsnj** [comment] 2017-09-01 15:35
OK, I have narrowed it down to 1 of the 2 scripts in that cron job throwing the error (mailwatch_postfix_relay.php is the one doing it - the other one throws no errors).

Here is a sample from my maillog (both MailScanner and Postfix are logging to the same place...should I be separating them?

Sep  1 09:42:14 mailscanner MailScanner[5356]: Requeue: 063FD412A2FC.A8366 to 3xkMQZ2lqtz55kZ
Sep  1 09:42:14 mailscanner MailScanner[5356]: Uninfected: Delivered 1 messages
Sep  1 09:42:14 mailscanner postfix/qmgr[4673]: 3xkMQZ2lqtz55kZ: from=<root@mailscanner.snjlaw.local>, size=286, nrcpt=1 (queue active)
Sep  1 09:42:14 mailscanner MailScanner[5356]: Deleted 1 messages from processing-database
Sep  1 09:42:14 mailscanner MailScanner[5356]: MailWatch: Logging message 063FD412A2FC.A8366 to SQL
Sep  1 09:42:14 mailscanner postfix/smtp[4676]: 3xkMQZ2lqtz55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=20, delays=20/0/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:42:14 mailscanner postfix/cleanup[4610]: 62315412A2FC: message-id=<20170901144214.62315412A2FC@mailscanner.snjlaw.local>
Sep  1 09:42:14 mailscanner postfix/qmgr[4673]: 62315412A2FC: from=<>, size=2580, nrcpt=1 (queue active)
Sep  1 09:42:14 mailscanner postfix/bounce[4582]: 3xkMQZ2lqtz55kZ: sender non-delivery notification: 62315412A2FC
Sep  1 09:42:14 mailscanner postfix/qmgr[4673]: 3xkMQZ2lqtz55kZ: removed
Sep  1 09:42:14 mailscanner postfix/local[4677]: 62315412A2FC: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.01, delays=0/0/0/0.01, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:42:14 mailscanner postfix/qmgr[4673]: 62315412A2FC: removed
Sep  1 09:42:14 mailscanner MailScanner[5396]: Connected to Processing Attempts Database
Sep  1 09:42:14 mailscanner MailScanner[5396]: Found 0 messages in the Processing Attempts Database
Sep  1 09:42:14 mailscanner MailScanner[5396]: Using locktype = flock
Sep  1 09:42:27 mailscanner postfix/postfix-script[5416]: stopping the Postfix mail system
Sep  1 09:42:27 mailscanner postfix/master[1869]: terminating on signal 15
Sep  1 09:42:27 mailscanner postfix/postfix-script[5498]: starting the Postfix mail system
Sep  1 09:42:27 mailscanner postfix/master[5500]: daemon started -- version 2.10.1, configuration /etc/postfix
Sep  1 09:42:31 mailscanner postfix/pickup[5501]: 797F0412A2FC: uid=0 from=<root>
Sep  1 09:42:31 mailscanner postfix/cleanup[5505]: 797F0412A2FC: hold: header Received: by mailscanner.snjlaw.local (Postfix, from userid 0)??id 797F0412A2FC; Fri,  1 Sep 2017 09:42:31 -0500 (CDT) from local; from=<root@mailscanner.snjlaw.local> to=<quintin@dictation.snj.ca>
Sep  1 09:42:31 mailscanner postfix/cleanup[5505]: 797F0412A2FC: message-id=<20170901144231.797F0412A2FC@mailscanner.snjlaw.local>
Sep  1 09:42:31 mailscanner MailScanner[5345]: New Batch: Scanning 1 messages, 528 bytes
Sep  1 09:42:31 mailscanner MailScanner[5345]: Virus and Content Scanning: Starting
Sep  1 09:42:45 mailscanner MailScanner[5345]: Requeue: 797F0412A2FC.A8BB6 to 3xkMR93k4zz55kZ
Sep  1 09:42:45 mailscanner MailScanner[5345]: Uninfected: Delivered 1 messages
Sep  1 09:42:45 mailscanner postfix/qmgr[5502]: 3xkMR93k4zz55kZ: from=<root@mailscanner.snjlaw.local>, size=286, nrcpt=1 (queue active)
Sep  1 09:42:45 mailscanner MailScanner[5345]: Deleted 1 messages from processing-database
Sep  1 09:42:45 mailscanner MailScanner[5345]: MailWatch: Logging message 797F0412A2FC.A8BB6 to SQL
Sep  1 09:42:45 mailscanner postfix/smtp[5532]: 3xkMR93k4zz55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=16, delays=16/0.02/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:42:45 mailscanner postfix/cleanup[5505]: 893E1412A2FC: message-id=<20170901144245.893E1412A2FC@mailscanner.snjlaw.local>
Sep  1 09:42:45 mailscanner postfix/bounce[5533]: 3xkMR93k4zz55kZ: sender non-delivery notification: 893E1412A2FC
Sep  1 09:42:45 mailscanner postfix/qmgr[5502]: 893E1412A2FC: from=<>, size=2580, nrcpt=1 (queue active)
Sep  1 09:42:45 mailscanner postfix/qmgr[5502]: 3xkMR93k4zz55kZ: removed
Sep  1 09:42:45 mailscanner postfix/local[5534]: 893E1412A2FC: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.03, delays=0/0.02/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:42:45 mailscanner postfix/qmgr[5502]: 893E1412A2FC: removed
Sep  1 09:43:44 mailscanner postfix/smtpd[5557]: warning: hostname thedirect-mailer.net does not resolve to address 94.102.51.31: Name or service not known
Sep  1 09:43:44 mailscanner postfix/smtpd[5557]: connect from unknown[94.102.51.31]
Sep  1 09:43:45 mailscanner postfix/smtpd[5557]: disconnect from unknown[94.102.51.31]
Sep  1 09:44:46 mailscanner postfix/smtpd[5557]: warning: hostname systemip3.example.com does not resolve to address 91.200.12.100: Name or service not known
Sep  1 09:44:46 mailscanner postfix/smtpd[5557]: connect from unknown[91.200.12.100]
Sep  1 09:44:47 mailscanner postfix/smtpd[5557]: lost connection after EHLO from unknown[91.200.12.100]

**Comment by quintingsnj** [comment] 2017-09-01 15:37
And here is a sample of the logs grepped on the word delay:

ep  1 09:01:19 mailscanner postfix/local[3660]: 3xkLWM0XZ1z55kZ: to=<root@mailscanner.snjlaw.local>, orig_to=<root>, relay=local, delay=17, delays=17/0.16/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:34:27 mailscanner postfix/smtp[4428]: 3xkMFb48Ynz55kf: to=<q@snj.ca>, relay=honda.snjlaw.local[192.168.0.4]:25, delay=20, delays=19/0.21/0.01/0.12, dsn=2.6.0, status=sent (250 2.6.0 <20170901143411.5F540412A2FD@mailscanner.snjlaw.local> [InternalId=14624363643078, Hostname=HONDA.snjlaw.local] Queued mail for delivery)
Sep  1 09:34:42 mailscanner postfix/smtp[4431]: 3xkMFn2qvMz55kY: to=<quintin@dictation.snj.ca>, relay=mail.snj.ca[192.168.0.4]:25, delay=23, delays=18/0.01/0.35/5, dsn=5.7.1, status=bounced (host mail.snj.ca[192.168.0.4] said: 550 5.7.1 Unable to relay (in reply to RCPT TO command))
Sep  1 09:34:52 mailscanner postfix/local[4443]: BDB76412A2FE: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.03, delays=0/0.03/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:39:14 mailscanner postfix/smtp[4580]: 3xkMM12kTVz55kZ: to=<quintin@dictation.snj.ca>, relay=mail.snj.ca[192.168.0.4]:25, delay=23, delays=18/0.14/0.04/5, dsn=5.7.1, status=bounced (host mail.snj.ca[192.168.0.4] said: 550 5.7.1 Unable to relay (in reply to RCPT TO command))
Sep  1 09:39:24 mailscanner postfix/local[4583]: 93A53412A2FD: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.04, delays=0/0.03/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:40:27 mailscanner postfix/smtp[4676]: 3xkMNW61B3z55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=17, delays=17/0.01/0.04/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:40:27 mailscanner postfix/local[4677]: DC2EA412A2FD: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.02, delays=0/0.02/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:41:23 mailscanner postfix/smtp[4676]: 3xkMPb1yXyz55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=16, delays=16/0/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:41:23 mailscanner postfix/local[4677]: 46D5E412A2FD: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.01, delays=0/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:42:14 mailscanner postfix/smtp[4676]: 3xkMQZ2lqtz55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=20, delays=20/0/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:42:14 mailscanner postfix/local[4677]: 62315412A2FC: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.01, delays=0/0/0/0.01, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:42:45 mailscanner postfix/smtp[5532]: 3xkMR93k4zz55kZ: to=<quintin@dictation.snj.ca>, relay=none, delay=16, delays=16/0.02/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:42:45 mailscanner postfix/local[5534]: 893E1412A2FC: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.03, delays=0/0.02/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:50:55 mailscanner postfix/smtp[5745]: 3xkMcZ5pZsz5XXj: to=<quintin@dictation.snj.ca>, relay=none, delay=21, delays=21/0.32/0.01/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=viper.snjlaw.llocal type=AAAA: Host not found)
Sep  1 09:50:55 mailscanner postfix/local[5747]: 349DB412EDC4: to=<root@mailscanner.snjlaw.local>, relay=local, delay=0.04, delays=0.01/0.03/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 09:51:02 mailscanner postfix/smtp[5745]: 3xkMcj6mz2z5F5v: to=<q@snj.ca>, relay=honda.snjlaw.local[192.168.0.4]:25, delay=17, delays=17/0/0.01/0.13, dsn=2.6.0, status=sent (250 2.6.0 <20170901145046.B19E24138AB3@mailscanner.snjlaw.local> [InternalId=14624363643197, Hostname=HONDA.snjlaw.local] Queued mail for delivery)
Sep  1 09:53:19 mailscanner postfix/smtp[5836]: 3xkMgL6Bx5z5XXg: to=<quintin@dictation.snj.ca>, relay=viper.snjlaw.local[192.168.0.1]:25, delay=18, delays=18/0.02/0.01/0.14, dsn=2.0.0, status=sent (250 Queued (0.110 seconds))
Sep  1 10:01:21 mailscanner postfix/local[6099]: 3xkMrd1KkRz5XXv: to=<root@mailscanner.snjlaw.local>, orig_to=<root>, relay=local, delay=18, delays=18/0.03/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep  1 10:19:06 mailscanner postfix/smtp[6610]: 3xkNF64vfmz5XY7: to=<q@snj.ca>, relay=honda.snjlaw.local[192.168.0.4]:25, delay=19, delays=19/0.02/0.01/0.15, dsn=2.6.0, status=sent (250 2.6.0 <8472d3ba17664e4b9c21a47821b5b78a@HONDA.snjlaw.local> [InternalId=14628658610277, Hostname=HONDA.snjlaw.local] Queued mail for delivery)

**Comment by asuweb** [comment] 2017-09-01 15:37
This is likely caused when delay is >60, as it's malformed. 

I've just checked on my live system, and when the delay is >60s, it displays as 00:00:00 in the mailwatch Relay Information.

We can fix this by using `SEC_TO_TIME` in the `REPLACE` statement I think

**Comment by asuweb** [comment] 2017-09-01 15:43
@quintingsnj - can you try the fix in PR #942

**Comment by quintingsnj** [comment] 2017-09-01 15:52
That did it!

Thanks!

**Comment by Skywalker-11** [comment] 2017-09-04 14:16
can be closed

**Closed** 2017-09-05 16:09 UTC
