### ISSUE TITLE
Possible Bug: cannot see total recipients in mailwatch mail

### ISSUE THREAD

**Issue by huloza** [mailwatch/MailWatch#871] opened 2017-06-22 22:08 UTC
So i have my account configured in Gmail, i sent an email to two people, both received the mail but in MailWatch only appears one recipient. when i access to details i can see the two recipients in TO: header, but in main screen only appears one. 

i attach the screens, and the server exim log. 

Im using Mailwatch 1.2.2 in Debian 8.8

##Message Listings
![imagen1](https://user-images.githubusercontent.com/12040815/27458097-687a7ccc-5775-11e7-9202-b61e26ba1ac2.PNG)

## Message Details
![imagen2](https://user-images.githubusercontent.com/12040815/27458096-687a23a8-5775-11e7-8da3-32cc72239ccc.PNG)

## EXIM LOG
```
2017-06-22 16:50:51 1dO93y-0005hQ-Sj <= me@sender.com H=mail-qt0-f173.google.com [209.85.216.173] P=esmtpsa X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:$
2017-06-22 16:50:51 1dO93y-0005hP-TN <= me@sender.com H=mail-qt0-f172.google.com [209.85.216.172] P=esmtpsa X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:$
2017-06-22 16:50:55 1dO93y-0005hP-TN => recipient1@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [66.102.1.27] X=TLS1.2:ECDHE_RSA_AES_128_G$
2017-06-22 16:50:55 1dO93y-0005hP-TN Completed
2017-06-22 16:50:55 1dO93y-0005hQ-Sj => eavila <recipient2@recipient.com> R=localuser T=local_delivery
2017-06-22 16:50:55 1dO93y-0005hQ-Sj Completed
```

Regards!

**Comment by Skywalker-11** [comment] 2017-06-22 23:18
That are two different mails. One with internal exim id `1dO93y-0005hP-TN` and one with `1dO93y-0005hQ-Sj`.
You are viewing the `1dO93y-0005hP-TN` and there should be an other entry for the other one.

Not a bug

**Comment by huloza** [comment] 2017-06-23 00:07
there is no other entry in the listing, and if the same mail was for two recipients should be show as follows:

![mailwatch2](https://user-images.githubusercontent.com/12040815/27461228-659542a6-5786-11e7-9694-3d2b4ec22df2.PNG)

**Comment by stefaweb** [comment] 2017-06-23 06:29
If I well understand.

One is an "local" mail (R=localuser), the second an external mail (T=remote).

The local mail goes directly in /va/spool/mail for local delivery, the second cross MS and output.

I suggest you to do not put the smtp/pop server on the same server as MS/MW.

**Comment by huloza** [comment] 2017-06-23 20:16
so its more a bad configured mta and not a MS problem right ?

**Comment by Skywalker-11** [comment] 2017-11-30 19:36
@huloza were you able to resolve this?

**Comment by huloza** [comment] 2017-11-30 19:49
No, i just updated Mailwatch, for the moment i didnt noticed again the problem.

**Comment by stefaweb** [comment] 2017-11-30 19:54
@huloza!
If the problem is no longer present. Please close the Issue.

**Closed** 2017-11-30 19:55 UTC
