### ISSUE TITLE
Missing option to see if a message was released from quarantine

### ISSUE THREAD

**Issue by KHIT93** [mailwatch/MailWatch#746] opened 2017-04-12 17:19 UTC
### Issue summary
It is currently not possible to see if a message was released from quarantine using the GUI or the maillog table in the database.

### Steps to reproduce
1. Release a quarantined message from `detail.php`, could get be spam, rblspam, virusinfected or something else that was quarantined.
2. The message is succesfully delivered to the destination email server
3. Visit `detail.php` and see that there is no information about the message having been released from quarantine.

### Expected result
There should either be a log entry with relation to the message that can be used to track it or a flag bit on the maillog record to indicate that it has been released

### Actual result
It is currentkly possible to find information about the release of a message in the audit log, but there is no relation in the database to allow for finding this and also no information for the user when the go back to a previous message that they do not remember if they have released or not.

### Version and method
 - MailWatch Version: 1.2.2
 - Install type: Any
 - Updated from an older MailWatch or fresh install: Any

### Server configuration
 - Operation System: CentOS 6.8
 - PHP version: 5.3.3
 - Database: MySQL
 - Mail Server: Sendmail
 - Used web server: Apache 2.2

### Client configuration 
Any

**Comment by endelwar** [comment] 2017-04-13 08:39
duplicate of #124

**Comment by Skywalker-11** [comment] 2017-05-25 10:44
can be closed

**Closed** 2017-05-31 17:32 UTC
Labels: enhancement
