### ISSUE TITLE
MailWatch error after a while writing into MYSQL

### ISSUE THREAD

**Issue by Lichengchang** [mailwatch/MailWatch#428] opened 2017-01-23 08:46 UTC
Hi,
I have the following problem.
Error：
Jan 23 09:03:50 mg1 MailScanner[13818]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xBCw\xA9g\xAFM...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 138, <CLIENT> line 439.

Frequency after this error appears is about 3-6 times per day.
After this error i get on MailScanner child which is stuck, and i get no new rows into my maillog MYSQL table.
I have to kill that >stuck< MailScanner child and restart MailScanner, after which my system is working again with no problems.
Should anyone come up with any ideas I would appreciate.
Thank you.

**Comment by stefaweb** [comment] 2017-01-23 08:48
What are the version of MailWatch, MailScanner and OS are you using?

**Comment by Lichengchang** [comment] 2017-01-23 10:19
OS：centos 6.8
MailScanner：5.0.3-7
MailWatch：1.2

**Comment by stefaweb** [comment] 2017-01-23 10:22
MailWatch 1.2 RC4 or previous version (RC1, RC2, etc.)?

**Comment by Lichengchang** [comment] 2017-01-23 10:45
How to check the version of MailWatch ?

**Comment by asuweb** [comment] 2017-01-23 10:48
Software Versions after logging into mailwatch 

![image](https://cloud.githubusercontent.com/assets/13250955/22200966/7ba6baaa-e159-11e6-9bf8-184b95005975.png)

**Comment by Lichengchang** [comment] 2017-01-23 12:14
![ldap3](https://cloud.githubusercontent.com/assets/25293877/22203528/7babbe7a-e1a8-11e6-8cf2-42ac3849be8c.png)

**Comment by stefaweb** [comment] 2017-01-23 12:25
Seems related with database structure.

Check database structure.
Run upgrade script form develop branch.

https://github.com/mailwatch/1.2.0/blob/develop/upgrade.php

**Comment by stefaweb** [comment] 2017-01-23 12:43
Oops, your PHP version is very very old and no longer supported.

**Comment by Lichengchang** [comment] 2017-01-24 01:06
So first upgrade php then run upgrade script?

recommend php version?

**Comment by Lichengchang** [comment] 2017-01-24 04:03
I find out some reports function cannot use, appear error message.

is there any correlation between new qustion and old

【Total Messages by Date】 error：
Notice: Trying to get property of non-object in /var/www/html/mailscanner/rep_total_mail_by_date.php on line 154 Error: no rows retrieved from database

【Top Viruses】error：
Notice: Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/html/mailscanner/rep_top_viruses.php on line 75 Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /var/www/html/mailscanner/rep_top_viruses.php on line 75 Notice: Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/html/mailscanner/rep_top_viruses.php on line 75 Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /var/www/html/mailscanner/rep_top_viruses.php on line 75 Notice: Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/html/mailscanner/rep_top_viruses.php on line 75 Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /var/www/html/mailscanner/rep_top_viruses.php on line 75

Notice: Trying to get property of non-object in /var/www/html/mailscanner/rep_top_sender_domains_by_quantity.php on line 74 Error: no rows retrieved from database

**Comment by Skywalker-11** [comment] 2017-01-24 07:48
With which php version does thus occure?

**Comment by Lichengchang** [comment] 2017-01-24 09:16
PHP 5.3.3

**Comment by Skywalker-11** [comment] 2017-01-24 09:20
Can you upgrade php and then try again? Like Stefan mentioned that version is not supported

**Comment by Lichengchang** [comment] 2017-01-24 09:47
recommend php version?

**Comment by stefaweb** [comment] 2017-01-24 09:51
PHP 5.6+ (or at minimum 5.5)
Upgrade PHP first and after run upgrade.php script from develop.

**Comment by Skywalker-11** [comment] 2017-01-24 11:04
You probably have to external packages because centos only support php up to 5.4 in version centos7

**Comment by Lichengchang** [comment] 2017-01-25 02:42
Hi,

I upgrade php version to 7.1 then run upgrade.php.
Web page show Testing connectivity to the database ...... then nothing happened

**Comment by asuweb** [comment] 2017-01-25 08:02
Anything in the error logs?

**Comment by Lichengchang** [comment] 2017-01-25 08:57
![img1](https://cloud.githubusercontent.com/assets/25293877/22283761/ef13d2d6-e31e-11e6-9c3f-ab8c8f5b8104.png)

what should I do?

**Comment by stefaweb** [comment] 2017-01-25 09:19
"user" should be max length 191 with utf8mb4.unicode.
Seems an error in the upgrade.php.

**Comment by Lichengchang** [comment] 2017-01-25 10:54
![img1](https://cloud.githubusercontent.com/assets/25293877/22287901/a2774b40-e32f-11e6-92a4-3a2cabf34e49.png)

what should I do?

**Comment by Skywalker-11** [comment] 2017-01-25 11:14
The problem is that we first convert everything to utf-8. If utf8mb4 support is there we try to convert to it but it fails because the length of the fields are 255 (not 191 what is needed for utf8mb4)

**Comment by Skywalker-11** [comment] 2017-01-25 11:18
try executing the following in mysql then execute upgrade.php again

```
ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `username` `username` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `fullname` `fullname` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by Skywalker-11** [comment] 2017-01-25 11:24
will create a seperate issue for that

**Comment by Lichengchang** [comment] 2017-01-25 15:48
Has been successfully executed following in mysql.

ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `username` `username` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `fullname` `fullname` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

Still display same error message：
 - Enlarge password field in `users` table............................ ERROR
Database error: Data truncated for column 'password' at row 2 - SQL = 'ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''

**Comment by stefaweb** [comment] 2017-01-25 16:04
Try the complete list of upgrade directly in phpmyadmin.
Do a backup of the database before.

```
ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `username` `username` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `fullname` `fullname` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE spamscores CHANGE user user VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE audit_log CHANGE user user VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE autorelease CHANGE msg_id msg_id VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE autorelease CHANGE uid uid VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE mcp_rules CHANGE rule_desc rule_desc VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE user_filters CHANGE username username VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

**Comment by stefaweb** [comment] 2017-01-25 16:30
`Data truncated for column 'password' at row 2`

You may be have a password already filing more than 191. 
Delete it

**Comment by Skywalker-11** [comment] 2017-01-25 17:49
The restriction for 191 character is only important if it is used in a primary key. Else it can be longer. So there is no reason to truncate password

**Comment by stefaweb** [comment] 2017-01-25 18:21
Sorry for this misunderstanding.

**Comment by stefaweb** [comment] 2017-01-26 09:51
Hello!
I've pushed a new version of upgrade.php if you want to try.
#441

**Comment by Lichengchang** [comment] 2017-02-06 03:40
Whitch version for upgrade.php should i use?

**Comment by Lichengchang** [comment] 2017-02-06 03:42
Sorry for during the chinese new year.

Which version for upgrade.php should i use?

**Comment by stefaweb** [comment] 2017-02-06 09:07
You should do this:

- use PHP 5.4 or 5.5 or 5.6 (not 7 with RC4).
- run upgrade.php from develop (https://github.com/mailwatch/1.2.0/blob/develop/upgrade.php)
- use *.pm mailwatch files from PR #425

But I will suggest you to wait for last version of MailWatch which will be published officially later in the month. You will be sure that the code will be in sync and verified.

**Comment by Lichengchang** [comment] 2017-02-07 05:48
Hi,
I downgrade PHP to 5.6 and run upgrade.php following：
![img2](https://cloud.githubusercontent.com/assets/25293877/22679291/f33c10fe-ed3b-11e6-9d5f-e5656c718c0b.png)

This is normal?

**Comment by Lichengchang** [comment] 2017-02-07 08:47
Hi,

The letter is in Chinese, but subject is garbled. following：

![image 3](https://cloud.githubusercontent.com/assets/25293877/22683678/0a8705d0-ed54-11e6-9a72-70bc6a13cc22.png)

But 'Message Headers' is normal in detail. 
![image 4](https://cloud.githubusercontent.com/assets/25293877/22683870/f997e720-ed54-11e6-9343-2782887253e1.png)

Should anyone come up with any ideas I would appreciate.

Thank you.

**Comment by Lichengchang** [comment] 2017-02-10 09:13
I deploy new condition and reinstall mailwatch.

Then I change some code in the database.php
In 58 line：
$charset = 'utf8mb4';

utf8mb4 change to utf8, Subject is normal.

**Comment by Skywalker-11** [comment] 2017-02-10 10:47
Problem should be fixed with updated pr #425. Can you try to use that files?
MailWatch.pm : [https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/MailWatch.pm](https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/MailWatch.pm)
SQLBlackWhite.pm: [https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/SQLBlackWhiteList.pm](https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/SQLBlackWhiteList.pm)
SQLSpamSettings(optional): [https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/SQLSpamSettings.pm](https://github.com/stefaweb/1.2.0/blob/451bffe4672768b8536e795dc02ab911328d14c5/MailScanner_perl_scripts/SQLSpamSettings.pm)

**Comment by Lichengchang** [comment] 2017-02-13 03:45
Hi ,
I use the three new files you mentioned

utf8 change to utf8mb4 in database.php, subject is garbled.

**Comment by Lichengchang** [comment] 2017-02-13 07:14
I use the three new files MailWatch.pm , SQLBlackWhite.pm , SQLSpamSettings.pm

Still some error, following：
Feb 13 13:33:42 mg3 MailScanner[22320]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xB3\\xC3\xA3\xA4\xE5...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 37.

**Comment by Lichengchang** [comment] 2017-02-15 08:05
Sometimes cameout this error message and sometimes did't.
After this error i get on MailScanner child which is stuck, and i get no new rows into my maillog MYSQL table.
Set up cron to kill MailScanner child and restart MailScanner services for every 20 munite.

Error message：
Feb 13 14:29:58 mg1 MailScanner[3598]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF3\xA4\xA7\xAB\xC3\xB7...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 138, <CLIENT> line 39.
Feb 14 01:51:43 mg1 MailScanner[15963]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xB1z\xA6n~ ...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 102.
Feb 14 07:30:29 mg1 MailScanner[20653]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xB3\xAF\xB2Q\xAA\xE2...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 35.
Feb 14 11:35:19 mg1 MailScanner[27014]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xC2\x0A    ...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 118.
Feb 14 15:06:16 mg1 MailScanner[30884]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xE9 \x90\xE8\xA8\x82...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 263.
Feb 14 18:16:56 mg1 MailScanner[5381]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xC7\xD7\xB0\xAE\xB5\xC4...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 47.
Feb 14 23:10:57 mg1 MailScanner[10051]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xC0s\xACWLZ...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 42.
Feb 15 01:42:36 mg1 MailScanner[12967]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xAA\xF7\xB6\xD7\xB0\xEA...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 82.
Feb 15 09:28:59 mg1 MailScanner[19950]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xB1\xD8\xB7\xA2 \xBA...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 91.
Feb 15 11:43:58 mg1 MailScanner[24117]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF6\xB2\xBB\xBB\xC3\xA1...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 52.
Feb 15 14:18:04 mg1 MailScanner[30460]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xB2\xB6\xD3\xE3" ...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 181, <CLIENT> line 286.

**Comment by DiederikvandenB** [comment] 2017-02-15 10:30
Can confirm that I am experiencing the same error. Based out of Europe by the way, no indication of weird/foreign characters in the emails. Only thing I can imagine is emoji maybe?

**Comment by Skywalker-11** [comment] 2017-02-15 17:09
@Lichengchang can you provide a mail that causes that error?

**Comment by Lichengchang** [comment] 2017-02-16 03:09
I don't understand what you said about the mail error means,cuz mail already been sended so i can't report the integral mail message to you.
Is mail log be helpful ?

**Comment by spec1re** [comment] 2017-02-16 06:46
this: https://github.com/mailwatch/1.2.0/issues/430#issuecomment-276671365

MailWatch needs to validate if the header is valid UTF-8 first (eg and not ANSI like in my case), before it tries to insert the header into MySQL (version 5.6 and above) or it will crash.

**Comment by DiederikvandenB** [comment] 2017-02-16 12:46
`Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF2\xCF\xD3\xD2\xC1\xC2...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 215, <CLIENT> line 161.`

Even with the new .pm files, still the same error.

I understand that switching to MariaDB might work fine, but I first want to try and get it fixed on MySQL.

**Comment by Lichengchang** [comment] 2017-02-17 02:05
@spec1re - Thanks, I will try to convert to MariaDB.

What version your recommend?  10.1.13?

**Comment by Lichengchang** [comment] 2017-02-17 02:08
@spec1re - Thanks, I will try to convert to MariaDB.

What version your recommend?

**Comment by Lichengchang** [comment] 2017-02-17 08:20
I convert to MariaDB, display error message.
Should anyone come up with any ideas I would appreciate.
Thank you.

![mg1](https://cloud.githubusercontent.com/assets/25293877/23057727/7635c336-f52c-11e6-9d84-ef052a598d6f.png)

**Comment by stefaweb** [comment] 2017-02-17 08:23
Perl DynaLoader library is missing.
For Debian: apt-get install libpar-perl
Or from CPAN: http://search.cpan.org/~shay/perl-5.24.1/ext/DynaLoader/DynaLoader_pm.PL

**Comment by spec1re** [comment] 2017-02-17 10:07
@Lichengchang - I'm using

```
mariadb101-client-10.1.21          
mariadb101-server-10.1.21  
```
right now.

**Comment by spec1re** [comment] 2017-02-17 10:08
@DiederikvandenB - You are totally right on that point.

**Comment by DiederikvandenB** [comment] 2017-02-20 01:52
I don't want to be a nuisance at all, but I was wondering whether there is some news on this bug? My logs are full with this error, and it always concerns the same `incorrect string value`: `\xE9\xDD\xC5\xD4\xC5`. I think I've debugged it to the point where this is simply an invalid UTF-8 string, but my Perl skills are not at all good enough to find a solution to the problem.

**Comment by Lichengchang** [comment] 2017-02-22 03:46
@DiederikvandenB - This problem has not been solved in MYSQL.

@spec1re - recommend 3 options：
1. downgrade to MySQL 5.5.
2. switch to MariaDB.
3. wait till the MailWatch Devs have a fix for that.

I choose 2, now it not crashing for a five days.

**Comment by stefaweb** [comment] 2017-02-22 12:44
> Jan 23 09:03:50 mg1 MailScanner[13818]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xBCw\xA9g\xAFM...' for column '**headers**' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 138, line 439.

Someone can try this:

stop mailcanner.

In MailWatch.pm change this line:

`$msg{headers} = join("\n", @{$message->{headers}});`

whith:

`$msg{headers} = join("\n", map { fix_latin($_)} @{$message->{headers}});`

start mailscanner.

Let me know if this solve your problem.

As well, you need to use the develop version of MailWatch.pm and the database schema need to be uptodate for utfm8bm4.

**Comment by DiederikvandenB** [comment] 2017-02-22 16:42
Thanks for your input. Will try this tonight. Unfortunately I don't know how to trigger the error so I won't know immediately whether it'll fix the bug.

Will get back to you.

**Comment by DiederikvandenB** [comment] 2017-02-27 11:41
So far the fix above seems to be working. Nothing's crashed ever since. However, as I mentioned earlier, it is also possible that we just haven't received any spam mail that would trigger the problem.

**Comment by DiederikvandenB** [comment] 2017-02-28 13:20
It seems like the fix has resolved the issue. Getting a few emails with the subject `õÖÅ ÒÁÂÏÔÁÅÛØ?` and nothing crashes. Thanks!

**Comment by stefaweb** [comment] 2017-02-28 14:26
Great. I was pretty sure as the problem was the same as with Subject:
Done in #556.

This issue can be closed.

**Comment by spec1re** [comment] 2017-03-01 12:10
@stefaweb - I just switched back from MariaDB to MySQL and can confirm, the above fix did the trick! No DB crashing anymore with invalid UTF8 headers and MySQL.

Thank you all so much. :)

**Closed** 2017-06-13 15:27 UTC
