### ISSUE TITLE
Deadlock found when trying to get lock (spamassassin & Bayes)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#819] opened 2017-05-30 14:45 UTC
### Issue summary

Found this in /var/log/daemon.log. No found yet where they come from.

Found 75 since this morning on a prod server.

```
May 30 12:37:21 localhost mysqld: 170530 12:37:21 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 14:03:26 localhost mysqld: 170530 14:03:26 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 14:03:26 localhost mysqld: 170530 14:03:26 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 14:04:57 localhost mysqld: 170530 14:04:57 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 14:16:25 localhost mysqld: 170530 14:16:25 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 15:11:14 localhost mysqld: 170530 15:11:14 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
May 30 15:32:56 localhost mysqld: 170530 15:32:56 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
```
### Version and method
 - MailWatch Version: 1.2.3 develop (from April 16)
### Server configuration
 - Operation System: Debian
 - PHP version: 5.6
 - Database: MariaDB version 10.0.31
 - Mail Server: Exim
 - Used web server: Apache version 2.4.10

**Comment by stefaweb** [comment] 2017-05-31 07:50
Found the problem. The problem was not in MailWatch but in Bayes database. An index was missing and was causing problem with InnoDB (and MariaDB 10.0.x).

For reference, the "uptodate" database schema for Bayes and AWL.

```
#Create MySQL tables (SA version 3.4.0).
CREATE TABLE bayes_expire (
  id int(11) NOT NULL default '0',
  runtime int(11) NOT NULL default '0',
  KEY bayes_expire_idx1 (id)
) ENGINE=InnoDB;

CREATE TABLE bayes_global_vars (
  variable varchar(30) NOT NULL default '',
  value varchar(200) NOT NULL default '',
  PRIMARY KEY  (variable)
) ENGINE=InnoDB;

INSERT INTO bayes_global_vars VALUES ('VERSION','3');

CREATE TABLE bayes_seen (
  id int(11) NOT NULL default '0',
  msgid varchar(200) binary NOT NULL default '',
  flag char(1) NOT NULL default '',
  PRIMARY KEY  (id,msgid)
) ENGINE=InnoDB;

CREATE TABLE bayes_token (
  id int(11) NOT NULL default '0',
  token binary(5) NOT NULL default '',
  spam_count int(11) NOT NULL default '0',
  ham_count int(11) NOT NULL default '0',
  atime int(11) NOT NULL default '0',
  PRIMARY KEY  (id, token),
  INDEX bayes_token_idx1 (id, atime)
) ENGINE=InnoDB;

CREATE TABLE bayes_vars (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(200) NOT NULL default '',
  spam_count int(11) NOT NULL default '0',
  ham_count int(11) NOT NULL default '0',
  token_count int(11) NOT NULL default '0',
  last_expire int(11) NOT NULL default '0',
  last_atime_delta int(11) NOT NULL default '0',
  last_expire_reduce int(11) NOT NULL default '0',
  oldest_token_age int(11) NOT NULL default '2147483647',
  newest_token_age int(11) NOT NULL default '0',
  PRIMARY KEY  (id),
  UNIQUE bayes_vars_idx1 (username)
) ENGINE=InnoDB;

CREATE TABLE awl (
        username varchar(100) NOT NULL default '',
        email varchar(255) NOT NULL default '',
        ip varchar(40) NOT NULL default '',
        count int(11) NOT NULL default '0',
        totscore float NOT NULL default '0',
        signedby varchar(255) NOT NULL default '',
        PRIMARY KEY (username, email, signedby, ip)
) ENGINE=InnoDB;
```

**Comment by stefaweb** [comment] 2017-05-31 08:58
Bad new. The error is still here. If someone have a idea?

```

SHOW ENGINE INNODB STATUS;

INSERT INTO bayes_token
               (id, token, spam_count, ham_count, atime)
               VALUES ('3','�#L\"�','0','1','1496220158')
               ON DUPLICATE KEY UPDATE spam_count = GREATEST(spam_count + '0', 0),
                                       ham_count = GREATEST(ham_count + '1', 0),
                                       atime = GREATEST(atime, '1496220158')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2064 page no 6297 n bits 384 index `PRIMARY` of table `bayes`.`bayes_token` trx table locks 1 total table locks 2  trx id 10794357 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** (2) TRANSACTION:
TRANSACTION 10794360, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
30 lock struct(s), heap size 6544, 29 row lock(s), undo log entries 58
MySQL thread id 83645, OS thread handle 0x7f84f37e3700, query id 4966299 localhost bayes update
INSERT INTO bayes_token
               (id, token, spam_count, ham_count, atime)
               VALUES ('3','�	Y�>','0','1','1496220159')
               ON DUPLICATE KEY UPDATE spam_count = GREATEST(spam_count + '0', 0),
                                       ham_count = GREATEST(ham_count + '1', 0),
                                       atime = GREATEST(atime, '1496220159')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 2064 page no 6297 n bits 384 index `PRIMARY` of table `bayes`.`bayes_token` trx table locks 1 total table locks 2  trx id 10794360 lock_mode X locks rec but not gap lock hold time 0 wait time before grant 0
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2064 page no 11633 n bits 352 index `PRIMARY` of table `bayes`.`bayes_token` trx table locks 1 total table locks 2  trx id 10794360 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** WE ROLL BACK TRANSACTION (2)
```

**Comment by Skywalker-11** [comment] 2017-05-31 09:04
Problem is probably the `on duplicate key UPDATE` but I don't know how you could solve it other than detect first if it exist and then use normal update query instead of insert

**Comment by stefaweb** [comment] 2017-05-31 09:06
Does this mean that the bayes database is corrupted?

(I don't have the error on the dev server)

**Comment by Skywalker-11** [comment] 2017-05-31 09:39
I think you have to threads that try to change the db row for id 3. I can imagine the process is like this (but I can be mistaken):

1. Thread 1 starts insert
2. Thread 2 starts insert
3. Thread 1 sees that the primary key 3 exists, sees that on duplicate key update is set for the table, tries to get lock
4. Thread 2 sees that the primary key 3 exists, sees that on duplicate key update is set for the table, tries to get lock
5. Neither thread 1 nor 2 can get the write lock because the other one has read access to it
6. Deadlock is detected and the transaction of one thread is discarded

**Comment by stefaweb** [comment] 2017-06-03 08:29
The error message is gone since yesterday 19H. Not found where the problem comes from. I suspect the Bayes base was corrupted and was cleaned by sa-learn.

**Comment by stefaweb** [comment] 2017-06-04 08:36
Problem gone.

**Comment by stefaweb** [comment] 2017-06-08 07:31
The problem is back.

I will try to upgrade my prod server to MariaDB 10.1 next days.

**Comment by stefaweb** [comment] 2017-06-11 11:19
I've installed the spamassassin backport 3.4.1-6~bpo8+1. No change.

The suspected code is in /usr/share/perl5/Mail/SpamAssassin/BayesStore/MySQL.pm

```
    my $sql = "INSERT INTO bayes_token
               (id, token, spam_count, ham_count, atime)
               VALUES (?,?,?,?,?)
               ON DUPLICATE KEY UPDATE spam_count = GREATEST(spam_count + ?, 0),
                                       ham_count = GREATEST(ham_count + ?, 0),
                                       atime = GREATEST(atime, ?)";

    my $sth = $self->{_dbh}->prepare_cached($sql);

(2 times in the code of MySQL.pm)

```

**Comment by Skywalker-11** [comment] 2017-11-30 19:37
@stefaweb does the problem still exist or can we close it?

**Comment by stefaweb** [comment] 2017-11-30 19:53
@Skywalker-11 

Seems still here.

`Nov 30 17:52:21 antispam2 mysqld: 171130 17:52:21 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction`

**Comment by Skywalker-11** [comment] 2017-11-30 20:49
I'm running bayes on mysql for a few month now on debian 9 and didn't notice the problem. I'm not using awl till now. But maybe it only ocures on instances with high traffic?

**Comment by endelwar** [comment] 2017-12-01 08:37
Are you using SATA drives on this server? If it is so the bottleneck can be the write performance of the disks: if you have enough ram you can try moving bayes database (only this database as explained here https://askubuntu.com/a/14421/219209) to a ramdisk. On my server I've only SSD disks (if I remember right also @Skywalker-11 uses ssd/nve disks) and this error never occurred (at least in the last 2 years of logs that I have)

**Comment by stefaweb** [comment] 2017-12-01 08:55
Hello!

The server is a Dell R430 with entreprise SSD (raid 5 with high end raid card). The VM is running under KVM with Jessie.

Should be ok. ;-)

**Comment by Skywalker-11** [comment] 2017-12-01 09:00
I have HDDs on a sas system under hyper-v so probably worse from performance view

**Comment by stefaweb** [comment] 2017-12-01 09:15
One more. On my dev server running MariaDB 10.1, I don't have the error message. But this server receive only 100 messages per day.

I'll will update MariaDB on the prod server to see.

**Comment by stefaweb** [comment] 2017-12-02 19:33
Upgraded to 10.1. No more Deadlock for the moment.

Will close the Issue Monday if confirmed.

**Comment by stefaweb** [comment] 2017-12-03 08:49
No luke. I still have the error. Less often than before but it is still there.

```
**Before 10.1**
Dec  2 16:20:10 antispam2 mysqld: 171202 16:20:10 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
**After 10.1 upgrade**
Dec  2 22:03:54 antispam2 mysqld[760]: 2017-12-02 22:03:54 139691794340608 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
Dec  3 02:40:31 antispam2 mysqld[760]: 2017-12-03  2:40:31 139691841399552 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
Dec  3 04:27:03 antispam2 mysqld[760]: 2017-12-03  4:27:03 139691794340608 [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction
```

**Comment by Skywalker-11** [comment] 2017-12-04 08:22
Are you running mariadb as standalone or cluster?

**Comment by stefaweb** [comment] 2017-12-04 08:34
Hi @Skywalker-11!

Standalone, all stuff is running on only one server.

**Comment by Skywalker-11** [comment] 2017-12-04 12:03
There is a bug report from 2007:
https://bz.apache.org/SpamAssassin/show_bug.cgi?id=5654

The only wayI can think of to prevent this would be to use an additional layer between MailScanner/SpamAssassin/Bayes and the mysqldb which executes the queries sequential. But this can cause a lot of other problems.
So no idea.
Issue may should be moved to spamassassin or to MailScanner as it is not MailWatch related

**Comment by Skywalker-11** [comment] 2018-02-19 11:14
I also got a deadlock today running the cleanup cron😞:
```
Fatal error: Uncaught mysqli_sql_exception: Deadlock found when trying to get lock; try restarting transaction in /opt/mailwatch/public/functions.php:972
Stack trace:
#0 /opt/mailwatch/public/functions.php(972): mysqli->query('DELETE FROM aut...')
#1 /usr/local/bin/mailwatch_quarantine_maint.php(88): dbquery('DELETE FROM aut...')
#2 /usr/local/bin/mailwatch_quarantine_maint.php(178): quarantine_clean()
#3 {main}
  thrown in /opt/mailwatch/public/functions.php on line 972
```
Debian 9. MariaDB Galera Cluster mysqld 10.1.26-MariaDB-0+deb9u1. MW 1.2.7

**Comment by thctlo** [comment] 2018-08-06 14:27
Hai, My setup: 
Debian 9, Mailwatch 1.2.7, mailscanner 5.0.7-2, postfix, spamassassin mariadb all debian stable.

What is used here, txrep or awl from spamassasin self? 

I use AWL, because there was a thing with txrep, can remember that. 
I dont have any Deadlocks, i did on my old server, not on stretch. 

I 've scripted the install, not complete finished but maybe you see something that helps. 

```
https://github.com/thctlo/debian-scripts/blob/master/stretch-mariadb-spamassassin-sql.sh 
```

**Comment by Skywalker-11** [comment] 2018-08-06 16:37
> What is used here, txrep or awl from spamassasin self?

Neither. Only bayes with sql backend (without awl). The error happened when running the quarantine_report cronjob.

>I 've scripted the install, not complete finished but maybe you see something that helps.

Well the crons that generated that error are missing in the script 😞 
I have a setup based on https://github.com/mailwatch/mailwatch-install-script. 
2 MS/MW instances on Debian 9 with enabled rpc and they are forming a MariaDB Galera cluster.

**Comment by thctlo** [comment] 2018-08-07 07:19
Hai, thanks for that link, i'll go through that one also, good to know. 

For the deadlocks. 
I did find the following very usesfull.
https://stackoverflow.com/questions/2596005/working-around-mysql-error-deadlock-found-when-trying-to-get-lock-try-restarti/9315578

https://dev.mysql.com/doc/refman/8.0/en/innodb-deadlocks.html

As far i did read the above and understand it, the deadlock are pretty normal. 
I did find also : https://translate.google.nl/translate?sl=auto&tl=en&js=y&prev=_t&hl=nl&ie=UTF-8&u=https%3A%2F%2Fyemaosheng.com%2F2009%2F01%2Fmysql-replication-issues%2F&edit-text=
but this one is about a master/slave setup, i dont know how that works for a Galera cluster.

**Comment by Skywalker-11** [comment] 2018-08-07 07:45
I guess the problem is that the query is taking too long searching the maillog and during that other queries try to access the same table.

There is also https://stackoverflow.com/a/918092 which could prevent it when only reading from the table

**Comment by thctlo** [comment] 2018-08-07 08:09
Do you use  mysqltuner? 
i just saw, that its included galera clusters checks also. It may give some hint for some optimization.

**Closed** 2019-12-18 12:48 UTC
Labels: server-configuration, wontfix
